spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO
    com.suraj.rag.documentprocessing: INFO

app:
  aws:
    region: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}
    sqs:
      endpoint: ${AWS_SQS_ENDPOINT:}
      document-ready-queue-url: ${DOCUMENT_READY_QUEUE_URL}
  events:
    publisher: ${DOCUMENT_EVENT_PUBLISHER:sqs}
